version: '3.9'

services:
    app:
      restart: always
      image: bohdanshlyah/crypto_currency_tracker_bot:latest
      command: >
        sh -c "python3 main.py"
      env_file: .env
      environment:
        - API_TOKEN=$API_TOKEN